language: node_js

node_js:
  - lts/*
  - node

install:
  - npm install
  - npm install -g codecov

after_success:
  - npm run report-coverage

script:
  - npm run lint
  - npm run build
  - npm test
